export const CONSTANTS = {
    // EDGE_BUFFER: 30,
    // WARM_UP_SECONDS: 1,
    CANVAS_HEIGHT: 800,
    CANVAS_WIDTH: 600,
    ROCK_HEIGHT: 30,
    ROCK_WIDTH: 70,
    CLIMBER_HEIGHT: 70,
    CLIMBER_WIDTH: 70,
    GRAVITY: 0.35
};

export function getVerticalGap() {
    return (CONSTANTS.CANVAS_HEIGHT - 40) / CONSTANTS.TOTAL_ROCKS;
}
